#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>

#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>

#include <vector>

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

/**
 * Set the socket to non-blocking mode.
 * @param fd socket handle.
 *
 */
static void fd_set_nb(int fd) {
    errno = 0;
    // fcntl is used to manipulate the properties of the file descriptor.
    // F_GETFL: Get file status flags (File_GetFlags)
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error: error retrieving flags.");
        return;
    }

    // |= is the bitwise OR, used instead of addition for the case that O_NONBLOCK might already be set (1000 + O_NONBLOCK would cause issues)
    // flags represent individual bits packed into an integer.
    // O_NONBLOCK = 0x0800 (1000 0000 0000), the 1 is important here, as it represents O_NONBLOCK.
    // The bitwise OR simply makes it so that any existing flags (individual bits) already set, will remain while this flag is also added.
    //
    flags |= O_NONBLOCK;

    errno = 0;
    // set the flags for the file descriptor.
    (void) fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error: error setting flags");
    }
}


// << means left shift operator, shift the bits for the number '32' left by 20 positions to the left.
// shifting left is the same as multiplying said number by 2^n, in this case, 32 x 2^20.
// simply a readable way to express the number of megabytes wanted in bytes.
// (32 << 10 = 32KB, 32 << 20 = 32MB, 32 << 30 = 32GB).
// kernel max message size is set to 32 Megabytes.
const size_t k_max_msg = 32 << 20;

/**
 * Conn struct represents an individual connection.
 *
 * @var fd socket handle, acts as the id.
 * @var want_read tells the event loop if the incoming buffer need to be read.
 * @var want_write tells the event loop if the outgoing buffer need to be flushed.
 * @var want_close tells the event loop if the connection need to be closed.
 * @var incoming message buffer, data that needs parsing.
 * @var outgoing message buffer, responses generated by the application.
 *
 */
struct Conn {
    int fd = -1;

    bool want_read = false;
    bool want_write = false;
    bool want_close = false;

    std::vector<uint8_t> incoming;
    std::vector<uint8_t> outgoing;
};

/**
 * Append data to the buffer.
 *
 * @param buf buffer to append the data to.
 * @param data memory address pointing to beginning data bytes.
 * @param len the length of the data.
 */
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len) {
    // starting at the end of the buffer, inserts the bytes between pointers data and data + len (the length of the data).
    buf.insert(buf.end(), data, data + len);
}

/**
 * Remove data from the buffer.
 *
 * @param buf the buffer to remove bytes from.
 * @param n the number of bytes to remove.
 */
static void buf_consume(std::vector<uint8_t> &buf, size_t n) {
    // removes all data in the range between the pointers provided and shifts down remaining data.
    buf.erase(buf.begin(), buf.begin() + n);
}
