#include <assert.h>
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
#include <stdio.h>
#include <errno.h>

#include <fcntl.h>
#include <poll.h>
#include <unistd.h>
#include <arpa/inet.h>
#include <sys/socket.h>
#include <netinet/ip.h>

#include <vector>

static void msg(const char *msg) {
    fprintf(stderr, "%s\n", msg);
}

static void msg_errno(const char *msg) {
    fprintf(stderr, "[errno:%d] %s\n", errno, msg);
}

static void die(const char *msg) {
    fprintf(stderr, "[%d] %s\n", errno, msg);
    abort();
}

/**
 * Set the socket to non-blocking mode.
 * @param fd socket handle.
 *
 */
static void fd_set_nb(int fd) {
    errno = 0;
    // fcntl is used to manipulate the properties of the file descriptor.
    // F_GETFL: Get file status flags (File_GetFlags)
    int flags = fcntl(fd, F_GETFL, 0);
    if (errno) {
        die("fcntl error: error retrieving flags.");
        return;
    }

    // |= is the bitwise OR, used instead of addition for the case that O_NONBLOCK might already be set (1000 + O_NONBLOCK would cause issues)
    // flags represent individual bits packed into an integer.
    // O_NONBLOCK = 0x0800 (1000 0000 0000), the 1 is important here, as it represents O_NONBLOCK.
    // The bitwise OR simply makes it so that any existing flags (individual bits) already set, will remain while this flag is also added.
    //
    flags |= O_NONBLOCK;

    errno = 0;
    // set the flags for the file descriptor.
    (void) fcntl(fd, F_SETFL, flags);
    if (errno) {
        die("fcntl error: error setting flags");
    }
}


// << means left shift operator, shift the bits for the number '32' left by 20 positions to the left.
// shifting left is the same as multiplying said number by 2^n, in this case, 32 x 2^20.
// simply a readable way to express the number of megabytes wanted in bytes.
// (32 << 10 = 32KB, 32 << 20 = 32MB, 32 << 30 = 32GB).
// kernel max message size is set to 32 Megabytes.
const size_t k_max_msg = 32 << 20;

/**
 * Conn struct represents an individual connection.
 *
 * @var fd socket handle, acts as the id.
 * @var want_read tells the event loop if the incoming buffer need to be read.
 * @var want_write tells the event loop if the outgoing buffer need to be flushed.
 * @var want_close tells the event loop if the connection need to be closed.
 * @var incoming message buffer, data that needs parsing.
 * @var outgoing message buffer, responses generated by the application.
 *
 */
struct Conn {
    int fd = -1;

    bool want_read = false;
    bool want_write = false;
    bool want_close = false;

    std::vector<uint8_t> incoming;
    std::vector<uint8_t> outgoing;
};

/**
 * Append data to the buffer.
 *
 * @param buf buffer to append the data to.
 * @param data memory address pointing to beginning data bytes.
 * @param len the length of the data.
 */
static void buf_append(std::vector<uint8_t> &buf, const uint8_t *data, size_t len) {
    // starting at the end of the buffer, inserts the bytes between pointers data and data + len (the length of the data).
    buf.insert(buf.end(), data, data + len);
}

/**
 * Remove data from the buffer.
 *
 * @param buf the buffer to remove bytes from.
 * @param n the number of bytes to remove.
 */
static void buf_consume(std::vector<uint8_t> &buf, size_t n) {
    // removes all data in the range between the pointers provided and shifts down remaining data.
    buf.erase(buf.begin(), buf.begin() + n);
}

/**
 * Accepts a new incoming client connection and wraps in a Conn object for the event loop to process.
 *
 * @param fd socket handle
 * @return conn object or null
 */
static Conn *handle_accept(int fd) {
    // Init empty sockaddr object.
    struct sockaddr_in client_addr = {};
    socklen_t addrlen = sizeof(client_addr);
    // accept returns new specific client fd.
    int connfd = accept(fd, (struct sockaddr *) &client_addr, &addrlen);
    if (connfd < 0) {
        msg_errno("accept() error");
        return NULL;
    }

    // print client ip address in host byte order
    uint32_t ip = client_addr.sin_addr.s_addr;
    fprintf(stderr, "new client from %u.%u.%u.%u:%u",
            ip & 255, (ip >> 8) & 255, (ip >> 16) & 255, ip >> 24 & 255,
            ntohs(client_addr.sin_port)
    );

    // set client connection to non-blocking
    fd_set_nb(connfd);

    // wrap client address in Conn object
    // assign the client fd to conn object and set want_read to true.
    Conn *conn = new Conn();
    conn->fd = connfd;
    conn->want_read = true;
    return conn;
}

/**
 * Retrieves data from a connection incoming data buffer and writes to the outgoing data buffer.
 *
 * @param conn the Conn object, holding details for a client connection.
 * @return false if there is not enough or too much data. true if the request is successfully processed.
 */
static bool try_one_request(Conn *conn) {
    // if incoming buffer size is smaller than 32 bit int representing the length, the buffer will not be consumed.
    if (conn->incoming.size() < 4) {
        return false;
    }

    // retrieves the data length, copying the first 4 bytes to the len variable.
    uint32_t len = 0;
    memcpy(&len, conn->incoming.data(), 4);
    // returns false and closes on len being too big
    if (len > k_max_msg) {
        msg("too long");
        conn->want_close = true;
        return false;
    }

    // check if the entire message has arrived (return false and wait for all data).
    if (4 + len > conn->incoming.size()) {
        return false;
    }
    // store the memory address for the actual data.
    const uint8_t *request = &conn->incoming[4];

    // print the request
    printf("client says: len:%d data: %.*s\n",
        len, len < 100 ? len : 100, request);

    // append the length and the request to the outgoing buffer
    buf_append(conn->outgoing, (const uint8_t *)&len, 4);
    buf_append(conn->outgoing, request, len);

    // remove the data from the incoming buffer.
    buf_consume(conn-> incoming, 4 + len);
    return true;
}

/**
 * Writes data from the outgoing byte buffer.
 * Allows for partial writes to prevent congestion in the event loop.
 *
 * @param conn conn object containing connection data.
 */
static void handle_write(Conn *conn) {
    // Check to see there are bytes in the outgoing buffer.
    assert(conn->outgoing.size() > 0);
    // Perform write, doesn't have to be a full write.
    ssize_t rv = write(conn->fd, &conn->outgoing[0], conn->outgoing.size());
    if (rv < 0 && errno == EAGAIN) {
        return;
    }
    if (rv < 0) {
        msg_errno("write() error");
        conn->want_close = true;
        return;
    }

    // Remove written data from the buffer.
    buf_consume(conn->outgoing, size_t(rv));

    // if no data left to send, want_write bool is set to false and want_read set to true.
    if (conn->outgoing.size() == 0) {
        conn->want_read = true;
        conn->want_write = false;
    }
}

/**
 * Read data from the connection and store in the incoming buffer.
 * If a complete request is received, it will be processed and the response will be stored in outgoing buffer.
 *
 * @param conn client conn object holding connection details.
 */
static void handle_read(Conn *conn) {
    // empty buffer with max size 64KB
    uint8_t buf[64 * 1024];
    // read data and store in buf
    ssize_t rv = read(conn->fd, buf, sizeof(buf));
    if (rv < 0 && errno == EAGAIN) {
        return;
    }

    if (rv < 0) {
        msg_errno("read() error");
        conn->want_close = true;
        return;
    }

    // if return value is 0, want_close will be set to true.
    if (rv == 0) {
        if (conn->incoming.size() == 0) {
            // no data in the buffer.
            msg("client closed");
        } else {
            // data in the buffer, but client closed connection.
            msg("unexpected EOF");
        }
        conn->want_close = true;
        return;
    }

    // append the bytes stored in the temp buffer to the incoming data buffer in the conn object.
    buf_append(conn->incoming, buf, (size_t)rv);


    // append data to outgoing buffer and remove from the input buffer.
    while (try_one_request(conn)) {}

    // set bools for conn object and call handle_write function.
    if (conn->outgoing.size() > 0) {
        conn->want_read = false;
        conn->want_write = true;
        return handle_write(conn);
    }
}